### PR TITLE
make zero conf work

### LINKED ISSUE #21: Zeroconf not working as expected
When enabling zero-conf , the behaviour should be the payment would be set as paid once funds are on the mempool. That is not happening! 

Tested on testnet!

Redirecting to URL is triggered even when no redirect URL is set

### PR DESCRIPTION
**Pull request by talvasconcelos**
Forgot migration for pending!

Closes #21

### CODE REVIEW

**Comment by motorina0** [comment]
Its just the migration that was added?
The rest is code formatting?

**Review by motorina0 — APPROVED** [review]

**Comment by talvasconcelos** [comment]
> Its just the migration that was added? The rest is code formatting?

yes, prettier wasn't working for a while, and now when i save it formats files!

**Review by dni — APPROVED** [review]
hotfix, does it mean it needs a release?

in the future i would just make a 2nd PR with prettier formatting upfront

**Comment by motorina0** [comment]
@talvasconcelos have ran the existing JMeter tests for this change (to check for regression bugs)?

**Pull request merged**
